### ISSUE TITLE
#ract

### ISSUE THREAD

**Issue by Awk34** [kentcdodds/egghead-redirect-in-javascript#1]
![screenshot-github com 2015-12-01 16-37-59](https://cloud.githubusercontent.com/assets/5545474/11515149/5ed97754-984a-11e5-81ee-194bdaed048b.jpg)

![screenshot-github com 2015-12-01 16-37-59_2](https://cloud.githubusercontent.com/assets/5545474/11515151/630b5d92-984a-11e5-99eb-f86cea72d477.jpg)

![screenshot-github com 2015-12-01 16-37-59_3](https://cloud.githubusercontent.com/assets/5545474/11515153/64c54300-984a-11e5-9bf1-08b9083f2a19.jpg)

![screenshot-github com 2015-12-01 16-37-59_4](https://cloud.githubusercontent.com/assets/5545474/11515154/6669a872-984a-11e5-8303-20f1d2556b9c.jpg)

**Comment by kentcdodds** [comment]
lol, nice catch :-)

**Comment by Awk34** [comment]
:laughing:
